### PR TITLE
Update mypy and add python 3.8 support

### PR DESCRIPTION
**Pull request by kclowes**
## What was wrong?
Going through and updating support for libraries. Old mypy doesn't work with python 3.8 (`fails with error: AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'`).

## How was it fixed?
Updated mypy to the latest version and added tests for python 3.8. Also had to update flake8 as well. 

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/eth-abi/blob/master/newsfragments/README.md)

[//]: # (See: https://eth-abi.readthedocs.io/en/latest/contributing.html#pull-requests)
- [x] Add entry to the [release notes](https://github.com/ethereum/eth-abi/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Review by fselmo — APPROVED** [review]
LGTM. Should we go ahead and remove python 3.6 support as well? 🤔

_edit: Also curious if 3.9 build would work as-is but otherwise we can add that in another PR_

**Comment by kclowes** [comment]
I'll add 3.9 in another PR. I've been hesitant to drop 3.6, because I'm afraid it might kick off another dependency hell situation, but might as well do that while we're at it. I'll do that in another PR too. Thanks!
